apiVersion: v1
kind: Service
metadata:
  name: promefana
  labels:
    app: promefana
    tier: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  type: NodePort
  selector:
    app: promefana
    tier: backend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000
      name: http
      protocol: TCP
