apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promefana
  labels:
    app: promefana
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - secrets
  - configmaps
  - pods
  verbs:
  - get
  - watch
  - list
